#!/bin/sh

case "$1" in
	start)
		/usr/lib/udisks/udisks-daemon &
		cd /home/pi/workspace/FloppyCoffee
		stdbuf -oL bin/main --monitor-disks | tee -a monitorLog &
	;;
	stop)
		cd /home/pi/workspace/FloppyCoffee
	    echo "Stopping script blah" >> stopRequested
    ;;
esac

exit 0
